<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RootNamespace>Capa_de_procesamiento_de_datos</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>AnyCPU;x64;x86</Platforms>
		<AssemblyName>Capa_de_procesamiento_de_datos</AssemblyName>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Resources\Logo_Arqui.png" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Resources\Logo_Arqui.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="11.0.0-preview.2.26159.112" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.24" />
		<PackageReference Include="Microsoft.SqlServer.Server" Version="1.0.0" />
		<PackageReference Include="NBomber" Version="6.3.0" />
		<PackageReference Include="NBomber.Contracts" Version="6.2.0" />
		<PackageReference Include="NBomber.Http" Version="6.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Capa de acceso de datos\Capa de acceso de datos.csproj" />
	</ItemGroup>

</Project>