<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Capa_de_procesamiento_de_datos</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="aSystem.Windows.Forms" Version="1.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
    <PackageReference Include="QuestPDF" Version="2024.7.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Capa de acceso de datos">
      <HintPath>..\Capa de acceso de datos\bin\Debug\net8.0-windows\Capa de acceso de datos.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
