<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RootNamespace>Capa_de_Presentación</RootNamespace>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationIcon>logo.ico</ApplicationIcon>
		<StartupObject>Capa_de_Presentación.Program</StartupObject>
		<AssemblyName>SistemaContable-Arquidiócesis</AssemblyName>
		<Platforms>AnyCPU;x64;x86</Platforms>
		<SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
		<NoWarn>$(NoWarn);CS8618;CS8600;CS8602;CS8604;CS8625;CS0105</NoWarn>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Settings1.Designer.cs" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Formularios\Formularios empleados y sacerdotes\j1jmqutt.lwc~" />
		<None Remove="Formularios\Formularios empleados y sacerdotes\jaj2gnb4.yzy~" />
		<None Remove="Settings1.settings" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="logo.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="11.0.0-preview.2.26159.112" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
		<PackageReference Include="Microsoft.Data.SqlClient.Extensions.Abstractions" Version="1.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.24" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="NBomber" Version="6.3.0" />
		<PackageReference Include="NBomber.Contracts" Version="6.2.0" />
		<PackageReference Include="NBomber.Http" Version="6.2.0" />
		<PackageReference Include="OpenTK" Version="4.9.4" />
		<PackageReference Include="OpenTK.GLControl" Version="4.0.2" />
		<PackageReference Include="QuestPDF" Version="2025.7.4" />
		<PackageReference Include="Spire.PDF" Version="11.11.1" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Capa de acceso de datos\Capa de acceso de datos.csproj" />
		<ProjectReference Include="..\Capa de procesamiento de datos\Capa de procesamiento de datos.csproj" />
	</ItemGroup>

</Project>