<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RootNamespace>Capa_de_Presentación</RootNamespace>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="aSystem.Windows.Forms" Version="1.0.0" />
		<PackageReference Include="System.Windows.Forms" Version="1.0.0" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.3" />
		<PackageReference Include="OpenTK" Version="4.9.4" />
		<PackageReference Include="OpenTK.GLControl" Version="4.0.2" />
		<PackageReference Include="QuestPDF" Version="2025.7.4" />
		<PackageReference Include="ZedGraph" Version="5.2.1" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="Emgu.CV">
	    <HintPath>bin\Debug\net8.0-windows\Emgu.CV.dll</HintPath>
	  </Reference>
		<Reference Include="FaceRecognition">
			<HintPath>..\..\..\Downloads\FaceRecognition.dll</HintPath>
		</Reference>
	</ItemGroup>


	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="RECONOCIMIENTO FACIAL\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Capa de acceso de datos\Capa de acceso de datos.csproj" />
		<ProjectReference Include="..\Capa de procesamiento de datos\Capa de procesamiento de datos.csproj" />
	</ItemGroup>

</Project>